samples: /working/lab_nicw/jiaZ/github/nanopore_paired_tumour_workflow/config/test.csv
run_mode: "germline"
pull_containers: false # if running on qimrb cluster, no need to pull containers

snv_calling:
    phased_snv_from: 'clair3'
    germline: ['clair3','deepvariant']
    somatic: ['clairs']
sv_calling:
    germline: ['sniffles']
    somatic: ['savana','severus','nanomonsv']

reference:
    build: GRCh38
    file: /working/lab_nicw/jiaZ/data/genome/reference.fasta

annotation:
    blacklist: /working/lab_nicw/jiaZ/data/hg38-blacklist.v2.bed.gz
    pon: /working/lab_nicw/jiaZ/data/pon/PoN_1000G_hg38.tsv.gz
    vntr: /working/lab_nicw/jiaZ/data/severus/human_GRCh38_no_alt_analysis_set.trf.bed
    control_panel_path: /working/lab_nicw/jiaZ/data/nanomonsv/hprc_year1_data_freeze_nanopore_minimap2_2_24_merge_control
    simple_repeat: /working/lab_nicw/jiaZ/data/nanomonsv/simpleRepeat.bed.gz
    gff: 

params:
    trim: true
    read_qs: 10
    headcrop: 40
    tailcrop: 20
    minlen: 100
    minsvlen: 50
