samples: /working/lab_nicw/jiaZ/github/nanopore_paired_tumour_workflow/config/test.csv
run_mode: "all"
pull_containers: false # if running on qimrb cluster, no need to pull containers

snv_calling:
    phased_snv_from: 'clair3'
    germline: ['clair3','deepvariant']
    somatic: ['clairs']
sv_calling:
    germline: ['sniffles']
    somatic: ['savana','severus','nanomonsv']

reference:
    build: GRCh38
    file: /working/lab_nicw/jiaZ/data/genome/reference.fasta

annotation:
    blacklist: /working/lab_nicw/jiaZ/data/hg38-blacklist.v2.bed.gz
    pon: /working/lab_nicw/jiaZ/data/pon/PoN_1000G_hg38.tsv.gz
    vntr: /working/lab_nicw/jiaZ/data/severus/human_GRCh38_no_alt_analysis_set.trf.bed
    control_panel_path: /working/lab_nicw/jiaZ/data/nanomonsv/hprc_year1_data_freeze_nanopore_minimap2_2_24_merge_control
    simple_repeat: /working/lab_nicw/jiaZ/data/nanomonsv/simpleRepeat.bed.gz
    gff: 

params:
    trim: true
    read_qs: 10
    headcrop: 40
    tailcrop: 20
    minlen: 100
    minsvlen: 50

## tool params
pepper:
  sif: /working/lab_nicw/jiaZ/imgs/pepper/pepper_deepvariant_r0.8.sif
  params: /working/lab_nicw/jiaZ/data/ont_models/margin_phase
  
deepvariant:
  run_as_steps: true
  gpu: /working/lab_nicw/jiaZ/imgs/deepvariant/deepvariant_v1.9.0-gpu.sif
  cpu: /working/lab_nicw/jiaZ/imgs/deepvariant/deepvariant_1.9.0.sif

deepsomatic: 
  gpu: /working/lab_nicw/jiaZ/imgs/deepsomatic/deepsomatic_v1.9.0-gpu.sif
  cpu: /working/lab_nicw/jiaZ/imgs/deepsomatic/deepsomatic_1.9.0.sif

clair3:
  sif: /working/lab_nicw/jiaZ/imgs/clair3/clair3_v1.1.2.sif
  model: /working/lab_nicw/jiaZ/data/ont_models/clair3_models/r1041_e82_400bps_sup_v520

clairS:
  sif: /working/lab_nicw/jiaZ/imgs/clairs/clairs_v0.3.1.sif
  platform: ont_r10_dorado_sup_5khz
  indel_calling: true
  subclone: false

nanomonsv:
  misc_scripts_path: /opt/nanomonsv_scripts