samples: /mnt/backedup/home/jiaZ/working/github/nanopore_paired_tumour_workflow/config/test.csv
run_mode: "all"

snv_calling:
    phased_snv_from: 'clair3'
    germline: ['clair3']
    somatic: ['clairs']
sv_calling:
    germline: ['sniffles']
    somatic: ['savana','severus','nanomonsv']

reference:
    build: GRCh38
    file: /mnt/backedup/home/jiaZ/working/data/genome/reference.fasta

annotation:
    blacklist: /mnt/backedup/home/jiaZ/working/data/hg38-blacklist.v2.bed.gz
    pon: /mnt/backedup/home/jiaZ/working/data/pon/PoN_1000G_hg38.tsv.gz
    vntr: /mnt/backedup/home/jiaZ/working/data/severus/human_GRCh38_no_alt_analysis_set.trf.bed
    control_panel_path: /mnt/backedup/home/jiaZ/working/data/nanomonsv/hprc_year1_data_freeze_nanopore_minimap2_2_24_merge_control
    simple_repeat: /mnt/backedup/home/jiaZ/working/data/nanomonsv/simpleRepeat.bed.gz
    gff: 

params:
    trim: true
    read_qs: 10
    headcrop: 40
    tailcrop: 20
    minlen: 100
    minsvlen: 50