### samples table
#samples: /mnt/backedup/home/jiaZ/working/dev/nanopore_paired_tumour_workflow/config/samples.csv
samples: /mnt/backedup/home/jiaZ/working/dev/nanopore_paired_tumour_workflow/config/test.csv
basecalling_mode: ['sup']

step: 'alignment'  ## can be basecalling, alignment, snv, all.

### genome assembly with index
reference:
    build: GRCh38
    file: /mnt/backedup/home/jiaZ/working/data/genome/reference.fasta


## config for tools and models path.
### models for basecalling
ont_model:
    r9:
        hac:
            canonical: /mnt/backedup/home/jiaZ/working/bioprojects/nanopore_celllines_benchmark/data/models/dna_r9.4.1_e8_hac@v3.3
            remora: /mnt/backedup/home/jiaZ/working/bioprojects/nanopore_celllines_benchmark/data/models/dna_r9.4.1_e8_hac@v3.3_5mCG_5hmCG@v0
        sup:
            canonical: /mnt/backedup/home/jiaZ/working/bioprojects/nanopore_celllines_benchmark/data/models/dna_r9.4.1_e8_sup@v3.3
            remora: /mnt/backedup/home/jiaZ/working/bioprojects/nanopore_celllines_benchmark/data/models/dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0
    r10:
        hac:
            canonical: /mnt/backedup/home/jiaZ/working/data/ont_models/dna_r10.4.1_e8.2_400bps_hac@v4.3.0
            remora: /mnt/backedup/home/jiaZ/working/data/ont_models/dna_r10.4.1_e8.2_400bps_hac@v4.3.0_5mCG_5hmCG@v2
        sup:
            canonical: /mnt/backedup/home/jiaZ/working/data/ont_models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0
            remora: /mnt/backedup/home/jiaZ/working/data/ont_models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v2

clair3:
    sif: /mnt/backedup/home/jiaZ/working/imgs/clair3_v1.0.5.sif
    model_r9: /opt/models/r941_prom_sup_g5014    ## clair3 suggests to use sup for hac data
    model_r10: /mnt/backedup/home/jiaZ/working/data/ont_models/clair3_models/r1041_e82_400bps_sup_v420

clairS:
    sif: /mnt/backedup/home/jiaZ/working/imgs/clairs_v0.1.6.sif
    platform:
        R9: ont_r9_guppy
        R10: ont_r10_dorado_5khz

deepvariant: 
    gpu: /mnt/backedup/home/jiaZ/working/imgs/deepvariant-gpu-1.6.0.sif
    cpu: /mnt/backedup/home/jiaZ/working/imgs/deepvariant-1.6.0.sif

pepper: 
    sif: /mnt/backedup/home/jiaZ/working/imgs/pepper_deepvariant_r0.8.sif

severus:
    vntr: /mnt/backedup/home/jiaZ/working/data/severus/human_GRCh38_no_alt_analysis_set.trf.bed

nanomonsv:
    misc_scripts_path: /mnt/backedup/home/jiaZ/working/local/nanomonsv_scripts
    simple_repeat: /mnt/backedup/home/jiaZ/working/data/nanomonsv/simpleRepeat.bed.gz
    control_panel_path: /mnt/backedup/home/jiaZ/working/data/nanomonsv/hprc_year1_data_freeze_nanopore_minimap2_2_24_merge_control

delly:
    path: /mnt/backedup/home/jiaZ/working/local/delly/delly
    bed:

filter:
    trim: False
    read_qs: 10
    headcrop: 40
    tailcrop: 20
    minlen: 100

gold_standard:
    somatic:
        COLO829: /working/genomeinfo/share/analysis/Waddell_-_LRS_PanCancer.wdl/VCFs/Colo-829.Colo-829.79b65d30-08ac-4111-8baf-9ca91ed692fd_vs_Colo-829.Colo-829-BL.71843404-6af6-43db-aad1-120b62d521a6.sp.vcf.gz
        HCC1937: /working/genomeinfo/share/analysis/Waddell_-_LRS_PanCancer.wdl/VCFs/HCC1937.HCC1937.c863a327-4c69-4685-99ce-d188f09ce207_vs_HCC1937.HCC1937BL.73a8364c-9799-4e66-aa11-378b21d40a03.sp.vcf.gz
    germline:
        COLO829_BL: /working/genomeinfo/share/analysis/Waddell_-_LRS_PanCancer.wdl/VCFs/Colo-829.Colo-829.79b65d30-08ac-4111-8baf-9ca91ed692fd_vs_Colo-829.Colo-829-BL.71843404-6af6-43db-aad1-120b62d521a6.gp.vcf.gz
        HCC1937_BL: /working/genomeinfo/share/analysis/Waddell_-_LRS_PanCancer.wdl/VCFs/HCC1937.HCC1937.c863a327-4c69-4685-99ce-d188f09ce207_vs_HCC1937.HCC1937BL.73a8364c-9799-4e66-aa11-378b21d40a03.gp.vcf.gz


## tool path: need to have them in a environment in the future.
### dorado path, since it updates so frequently, I will install in my own folders first.
dorado_latest: /mnt/backedup/home/jiaZ/working/local/dorado/dorado-0.5.1-linux-x64/bin/dorado

modkit: /mnt/backedup/home/jiaZ/working/local/modkit/v0.2.4/modkit
f5c: 
    cpu: /mnt/backedup/home/jiaZ/working/local/f5c/v1.3/f5c_x86_64_linux
    gpu: /mnt/backedup/home/jiaZ/working/local/f5c/v1.3/f5c_x86_64_linux_cuda

bamcov: /mnt/backedup/home/jiaZ/working/local/bamcov/bamcov
