pepper:
  sif: /working/lab_nicw/jiaZ/imgs/pepper/pepper_deepvariant_r0.8.sif
  
deepvariant:
  run_as_steps: false
  gpu: /working/lab_nicw/jiaZ/imgs/deepvariant/deepvariant_v1.9.0-gpu.sif
  cpu: /working/lab_nicw/jiaZ/imgs/deepvariant/deepvariant_1.9.0.sif

deepsomatic: 
  gpu: /working/lab_nicw/jiaZ/imgs/deepsomatic/deepsomatic_v1.9.0-gpu.sif
  cpu: /working/lab_nicw/jiaZ/imgs/deepsomatic/deepsomatic_1.9.0.sif

clair3:
  sif: /working/lab_nicw/jiaZ/imgs/clair3/clair3_v1.1.2.sif
  model: /working/lab_nicw/jiaZ/data/ont_models/clair3_models/r1041_e82_400bps_sup_v520

clairS:
  sif: /working/lab_nicw/jiaZ/imgs/clairs/clairs_v0.3.1.sif
  platform: ont_r10_dorado_sup_5khz
  indel_calling: true
  subclone: false

nanomonsv:
  misc_scripts_path: /opt/nanomonsv_scripts