executor: cluster-generic
cluster-generic-submit-cmd: "pbs-submit.py"
jobscript: "pbs-jobscript.sh"
cluster-generic-cancel-cmd: "qdel"
jobs: 500
use-envmodules: True
use-apptainer: True
printshellcmds: True
latency-wait: 15
retries: 0

default-resources:
  walltime: 2
  mem: 10
