executor: cluster-generic
cluster-generic-submit-cmd: "/mnt/backedup/home/jiaZ/working/dev/nanopore_paired_tumour_workflow/workflow/profiles/default/pbs-submit.py"
jobscript: "/mnt/backedup/home/jiaZ/working/dev/nanopore_paired_tumour_workflow/workflow/profiles/default/pbs-jobscript.sh"
#cluster-generic-status-cmd: "/mnt/backedup/home/jiaZ/working/dev/nanopore_paired_tumour_workflow/workflow/profiles/default/pbs-status.py"
jobs: 500
use-envmodules: True
printshellcmds: True
latency-wait: 15
retries: 0